services:
  admin_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - STORE_CORS=http://localhost:8000
      - ADMIN_CORS=http://localhost:7000,http://localhost:7001
      - AUTH_CORS=http://localhost:7000,http://localhost:7001
      - REDIS_URL=redis://localhost:6379
      - JWT_SECRET=supersecret
      - COOKIE_SECRET=supersecret